export const RECEIVE_ADRESS = 'receive_address'
export const RECEIVE_FOODTYPE = 'receive_foodtype'
export const RECEIVE_SHOPS = 'receive_shops'
export const RECEIVE_CODE = 'receive_code'
export const RECEIVE_USERINFO = 'receive_userinfo'
export const RECEIVE_CLEARUSERINFO = 'receive_clearuserinfo'
export const RECEIVE_SHOPGOODS = 'receive_goods'
export const RECEIVE_SHOPRATINGS = 'receive_ratings'
export const RECEIVE_SHOPINFO = 'receive_info'
export const INCREMENT_FOOD_COUNT = 'increment_food_count' // 增加food中的count
export const DECREMENT_FOOD_COUNT = 'decrement_food_count' // 减少food中的count
export const CLEAR_CART = 'clear_cart' // 清空购物车
export const SEARCH_SHOP = 'search_shop'